---
- name: Install AWX with Caddy
  hosts: all
  roles:
    - role: shubhamtatvamasi.magma.prerequisites
    - role: shubhamtatvamasi.magma.docker
    - role: shubhamtatvamasi.magma.kubernetes
    - role: shubhamtatvamasi.magma.openebs
    - role: shubhamtatvamasi.magma.metallb
    - role: shubhamtatvamasi.magma.nginx
    - role: cert_manager
    - role: operator
    - role: awx
      vars:
        awx_service_type: "ClusterIP"
    - role: ingress
