---
- name: Add Caddy Ingress Helm repository
  kubernetes.core.helm_repository:
    name: caddy-ingress
    repo_url: https://caddyserver.github.io/ingress

- name: Install Caddy Ingress Controller
  kubernetes.core.helm:
    name: caddy-ingress-controller
    chart_ref: caddy-ingress/caddy-ingress-controller
    release_namespace: caddy-system
    chart_version: "{{ caddy_ingress_chart_version }}"
    create_namespace: true
    values:
      ingressController:
        autotls: "{{ caddy_autotls }}"
        email: "{{ caddy_email }}"
