---
- name: Clone awx-operator repo
  git:
    repo: https://github.com/ansible/awx-operator.git
    dest: /tmp/awx-operator
    version: "{{ awx_operator_version }}"
    force: yes

- name: Install awx-operator
  command: make deploy
  args:
    chdir: /tmp/awx-operator
