---
- name: Add cert-manager Helm repository
  kubernetes.core.helm_repository:
    name: cert-manager
    url: https://charts.jetstack.io

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: cert-manager/cert-manager
    release_namespace: cert-manager
    chart_version: "{{ cert_manager_chart_version }}"
    create_namespace: true
    values:
      installCRDs: true

- name: Install Let's Encrypt ClusterIssuer
  kubernetes.core.k8s:
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-issuer
          solvers:
          - http01:
              ingress:
                ingressClassName: nginx
